### ISSUE TITLE
Crashes connecting to printer

### ISSUE THREAD

**Issue by o-jasper** [timschmidt/repsnapper#112] opened 2014-04-19 17:10 UTC
It doesnt succeed at connecting to the printer and crashes. Melzi running  'Marlin 1.0.0 RC2' 

    (repsnapper:28243): Gtk-WARNING **: Unable to locate theme engine in module_path: "equinox",
    Exception Key file does not have key 'WindowWidth' loading setting

Get the equinox messages for a lot of things.(not important) Had this for git version bca4028 and one before that.

**Comment by gralco** [comment] 2015-05-01 14:34
I experience the same thing as o-jasper, only I use a ttyACM* serial file instead.

I've applied the patch to pyserial that allows me to use a 250000 baudrate with Pronterface and Octoprint, but it still fails for Repsnapper.

**Comment by o-jasper** [comment] 2015-05-02 22:47
Could be the case.. Not sure, i'd think i'd notice that. More than a year ago though, and dont remember. Should try when near the printer again.

**Comment by m0n5t3r** [comment] 2015-09-18 19:15
I can confirm it won't select 250000 baud (I am using the latest tag, which is in the ubuntu repositories, but `src/printer/printer_serial.cpp` hasn't been modified since 2013, so I guess it's the latest code

**Comment by hurzl** [comment] 2015-09-21 15:33
Most probably fixed by be11945e2e89d73d14e5d4284b7213e5bfc44aa1

**Closed by hurzl** 2015-09-21 15:33 UTC
